server.port: 8080

spring.datasource:
  #url: jdbc:mysql://localhost:3306/idea?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  #username: admin
  #password: admin
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://idea-rds-mysql.c8kdjalqnuyw.us-west-2.rds.amazonaws.com:3306/idea?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  username: idea
  password: topsecret
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false